Coin Machine Learning Algorithm Practice
***

### Simple Example

In [9]:
import numpy as np
train_feature  = np.array([[10], [8], [5], [3], [1]])  # 공부시간
# 2차원 array로 만든 이유
# 현재는 feature를 단순화 하기위해 1가지 변수(공부시간)만 들어가 있지만, 
# 실제로는 여러 가지 feature들이 들어갈 수 있기 때문에 2차원으로 만들어준다.
# 1차원 index = i 번째 데이터에 접근, 2차원 index = i번째 feature에 접근
train_label_regression = np.array([100, 80, 50, 30, 10]) # 성적
train_label_binary_classification = np.array([1, 1, 1, 0, 0]) # Pass/Non Pass
train_label_multi_classification = np.array([1, 2, 3, 0, 0]) # A,B,C,F,F

#### numpy 쓰는 이유

In [10]:
# python list 사용
[1,2,3] * [1,2,3] # Error

TypeError: can't multiply sequence by non-int of type 'list'

In [11]:
# np 사용
# 연산이 편리함
np.array([1,2,3])*np.array([1,2,3])

array([1, 4, 9])

### Linear Regression

In [12]:
import random
# data
x_train = train_feature
y_train = train_label_regression
x_test = np.array([[6]])

W = random.uniform(0,20)

size = len(x_train)
cost = 0
gradient = 0
learning_rate = 0.01

#### GradientDescentOptimizer

In [13]:
for cnt in range(20):
    for i in range(size):
        hypothesis = W*x_train[i]
        cost += np.square(hypothesis-y_train[i]) # 차이값 제곱해서 더하기
        gradient += (hypothesis - y_train[i])*x_train[i]
    cost = cost/size #  평균구하기
    gradient = gradient/size
    descent = W - learning_rate * gradient
#     if cnt % 10 == 0 :
    print(f'cnt={cnt:2d}, cost={float(cost):10.4f}, descent= {float(descent):.5f}')
    W = descent

cnt= 0, cost=    8.2198, descent= 10.27358
cnt= 1, cost=    4.6229, descent= 10.12852
cnt= 2, cost=    1.5820, descent= 10.04836
cnt= 3, cost=    0.4095, descent= 10.01308
cnt= 4, cost=    0.0887, descent= 10.00082
cnt= 5, cost=    0.0178, descent= 9.99804
cnt= 6, cost=    0.0037, descent= 9.99826
cnt= 7, cost=    0.0009, descent= 9.99900
cnt= 8, cost=    0.0002, descent= 9.99955
cnt= 9, cost=    0.0001, descent= 9.99984
cnt=10, cost=    0.0000, descent= 9.99996
cnt=11, cost=    0.0000, descent= 10.00000
cnt=12, cost=    0.0000, descent= 10.00001
cnt=13, cost=    0.0000, descent= 10.00001
cnt=14, cost=    0.0000, descent= 10.00000
cnt=15, cost=    0.0000, descent= 10.00000
cnt=16, cost=    0.0000, descent= 10.00000
cnt=17, cost=    0.0000, descent= 10.00000
cnt=18, cost=    0.0000, descent= 10.00000
cnt=19, cost=    0.0000, descent= 10.00000


#### prediction

In [14]:
# 예측이라는 것은 결국 잘 학습된 모델()
prediction = W * x_test # 공부시간이 6시간일 때 점수 예측
prediction

array([[59.9999998]])

#### Multi variable Linear Regression

In [15]:
# (x1+x2)/2 = y 인 식에 대한 linear Regerssion
x_train = np.array([[100,90], [80, 90], [45, 55], [30, 20], [10, 0]])
y_train = np.array([[95], [85], [50], [25], [5]])
size = x_train.shape[0]
W = np.array([random.uniform(0,1),random.uniform(0,1)])
learning_rate = 5e-5

print("----------------------------------------------")
for cnt in range(2000):
    hypothesis = W*x_train
    cost = np.mean(np.square(np.sum(hypothesis, axis=1).reshape(size,1)-y_train)) # 차이값 제곱해서 더하기
    gradient = np.mean((np.sum(hypothesis, axis=1).reshape(size,1)-y_train)*x_train, axis=0)
    W = W - learning_rate * gradient
    if cnt % 200 == 0:
        print(f'cnt={cnt:2d}, cost={float(cost):10.4f}')
        print(f'w1 = {float(W[0]):.3f}, w2= {float(W[1]):.3f}')
        print("----------------------------------------------")

----------------------------------------------
cnt= 0, cost=  315.1448
w1 = 0.278, w2= 0.548
----------------------------------------------
cnt=200, cost=    0.6734
w1 = 0.418, w2= 0.582
----------------------------------------------
cnt=400, cost=    0.2477
w1 = 0.450, w2= 0.550
----------------------------------------------
cnt=600, cost=    0.0911
w1 = 0.470, w2= 0.530
----------------------------------------------
cnt=800, cost=    0.0335
w1 = 0.482, w2= 0.518
----------------------------------------------
cnt=1000, cost=    0.0123
w1 = 0.489, w2= 0.511
----------------------------------------------
cnt=1200, cost=    0.0045
w1 = 0.493, w2= 0.507
----------------------------------------------
cnt=1400, cost=    0.0017
w1 = 0.496, w2= 0.504
----------------------------------------------
cnt=1600, cost=    0.0006
w1 = 0.498, w2= 0.502
----------------------------------------------
cnt=1800, cost=    0.0002
w1 = 0.498, w2= 0.501
----------------------------------------------


In [16]:
x_test = np.array([[10,50]])
prediction = np.sum(W*x_test)
print(f'pridiction = {prediction:.3f}')

pridiction = 30.036


#### using sklearn

In [17]:
from sklearn import linear_model
lr_model = linear_model.LinearRegression()
lr_model.fit(x_train, y_train)
lr_model.coef_

array([[0.5, 0.5]])

In [18]:
# 우리가 만든 모델의 테스트 데이터 사용
# x_test = np.array([[10,50]])
lr_model.predict(x_test)

array([[30.]])

### Logistic Regression
- linear regression 모델을 logistic function을 통해서 binarry classification으로 변경시켜줌

In [19]:
x_train = train_feature
y_train = train_label_binary_classification
x_test = np.array([[3]])

logistic_regression_model = linear_model.LogisticRegression()
logistic_regression_model.fit(x_train,y_train)

LogisticRegression()

In [20]:
for i in range(1,10):
    prediction = logistic_regression_model.predict(np.array([[i]]))
    result = "합격" if prediction == 1 else '불합격'
    print(f'{i}시간 공부시 합격여부 = {result}')

1시간 공부시 합격여부 = 불합격
2시간 공부시 합격여부 = 불합격
3시간 공부시 합격여부 = 불합격
4시간 공부시 합격여부 = 불합격
5시간 공부시 합격여부 = 합격
6시간 공부시 합격여부 = 합격
7시간 공부시 합격여부 = 합격
8시간 공부시 합격여부 = 합격
9시간 공부시 합격여부 = 합격


### kNN(k - Nearest Neighbors)
- k개의 인접한 점의 분류 결과를 보고 새로운 점의 분류 결과를 예측함

In [21]:
x_train = np.array([
    [9, 2], # kick count, kiss count
    [8, 4], # kick count, kiss count
    [5, 0], # kick count, kiss count
    [4, 0], # kick count, kiss count
    [5, 2], # kick count, kiss count
    [2, 7], # kick count, kiss count
    [4, 8], # kick count, kiss count
    [3, 9], # kick count, kiss count
    [0, 9], # kick count, kiss count
    [1, 6], # kick count, kiss count
])
# y_train = np.array([[1],[1],[1],[1],[1],[0],[0],[0],[0],[0]])
y_train = np.array([1,1,1,1,1,0,0,0,0,0])

In [22]:
from sklearn import neighbors
clf = neighbors.KNeighborsClassifier(n_neighbors=3) # n_neighbors를 통해 k값을 조절 가능
clf.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [25]:
for i in range(1,10):
    kick_count = random.uniform(1,9)
    kiss_count = random.uniform(1,9)
    prediction = clf.predict(np.array([[kick_count, kiss_count]]))
    result = "액션영화" if prediction == 1 else '로맨스영화'
    print('----------------------------------------------------------------')
    print(f'kick = {kick_count:.0f}, kiss = {kiss_count:.0f}일 때 예측결과 = {result}')
print('----------------------------------------------------------------')

----------------------------------------------------------------
kick = 4, kiss = 2일 때 예측결과 = 액션영화
----------------------------------------------------------------
kick = 6, kiss = 6일 때 예측결과 = 로맨스영화
----------------------------------------------------------------
kick = 1, kiss = 9일 때 예측결과 = 로맨스영화
----------------------------------------------------------------
kick = 9, kiss = 7일 때 예측결과 = 액션영화
----------------------------------------------------------------
kick = 3, kiss = 7일 때 예측결과 = 로맨스영화
----------------------------------------------------------------
kick = 4, kiss = 2일 때 예측결과 = 액션영화
----------------------------------------------------------------
kick = 2, kiss = 2일 때 예측결과 = 액션영화
----------------------------------------------------------------
kick = 7, kiss = 6일 때 예측결과 = 액션영화
----------------------------------------------------------------
kick = 2, kiss = 4일 때 예측결과 = 로맨스영화
----------------------------------------------------------------


### Decision Tree(의사 결정 나무)
- 트리 구조의 분류기를 만들어서 분류

In [28]:
from sklearn import tree
x_train = train_feature
y_train = train_label_multi_classification
clf = tree.DecisionTreeClassifier()
clf.fit(x_train, y_train)

DecisionTreeClassifier()

In [29]:
for i in range(1,15):
    prediction = clf.predict(np.array([[i]]))
    result = chr(prediction+64) if prediction != 0 else 'F'
    print(f'{i:2d}시간 공부시 학점 예측 = {result}')

 1시간 공부시 학점 예측 = F
 2시간 공부시 학점 예측 = F
 3시간 공부시 학점 예측 = F
 4시간 공부시 학점 예측 = F
 5시간 공부시 학점 예측 = C
 6시간 공부시 학점 예측 = C
 7시간 공부시 학점 예측 = B
 8시간 공부시 학점 예측 = B
 9시간 공부시 학점 예측 = B
10시간 공부시 학점 예측 = A
11시간 공부시 학점 예측 = A
12시간 공부시 학점 예측 = A
13시간 공부시 학점 예측 = A
14시간 공부시 학점 예측 = A


##  (과제) 위 구현된 모델을 참고하여 아래의 3가지 모델에 대해서 자신이 간단히 조사하여<br>markdown을 작성하고 간단한 예제를 활용하여 예측 모델 구현
 - sklearn 공식 홈페이지 (https://scikit-learn.org/stable/index.html)
 - 데이터 셋은 자유롭게 가져오거나 본인이 창작하여 사용

### Random Forest
여러 개의 의사결정나무를 만들고 투표를 통해 다수결로 결과를 결정한다.
랜덤 포레스트는 배깅 기법 중 하나이다.
배깅 기법은 훈련세트를 여러 개의 샘플로 만들고 알고리즘마다 다른 훈련세트를 사용한다.

In [36]:
from sklearn.ensemble import RandomForestClassifier
x_train = train_feature
y_train = train_label_multi_classification
clfR = RandomForestClassifier(n_estimators=5)
clfR = clf.fit(x_train, y_train)

In [37]:
for i in range(1,15):
    prediction = clfR.predict(np.array([[i]]))
    result = chr(prediction+64) if prediction != 0 else 'F'
    print(f'{i:2d}시간 공부시 학점 예측 = {result}')

 1시간 공부시 학점 예측 = F
 2시간 공부시 학점 예측 = F
 3시간 공부시 학점 예측 = F
 4시간 공부시 학점 예측 = F
 5시간 공부시 학점 예측 = C
 6시간 공부시 학점 예측 = C
 7시간 공부시 학점 예측 = B
 8시간 공부시 학점 예측 = B
 9시간 공부시 학점 예측 = B
10시간 공부시 학점 예측 = A
11시간 공부시 학점 예측 = A
12시간 공부시 학점 예측 = A
13시간 공부시 학점 예측 = A
14시간 공부시 학점 예측 = A


### Naive Bayes algorithm
P(A|B) = P(B|A)P(A)/P(B)
스팸필터 및 키워드 검색을 활용한 문서분류에 사용된다.
데이터를 분류할 떄 데이터 셋의 모든 특징들이 독립적이고 동등하다고 가정하고 데이터를 분류한다.
적은 학습 데이ㅓ로도 잘 수행된다.
메모리 사용량이 적고 성능이 빠르다.
각 특징들이 독립적이지 않을 경우, 오류가 발생할 수 있다.

In [42]:
from sklearn.naive_bayes import GaussianNB
x_train = train_feature
y_train = train_label_binary_classification
x_test = np.array([[3]])

logistic_regression_model = linear_model.LogisticRegression()
logistic_regression_model.fit(x_train,y_train)

gnb = GaussianNB()
gnb.fit(x_train, y_train)

GaussianNB()

In [43]:
for i in range(1,10):
    prediction = gnb.predict(np.array([[i]]))
    result = "합격" if prediction == 1 else '불합격'
    print(f'{i}시간 공부시 합격여부 = {result}')

1시간 공부시 합격여부 = 불합격
2시간 공부시 합격여부 = 불합격
3시간 공부시 합격여부 = 불합격
4시간 공부시 합격여부 = 합격
5시간 공부시 합격여부 = 합격
6시간 공부시 합격여부 = 합격
7시간 공부시 합격여부 = 합격
8시간 공부시 합격여부 = 합격
9시간 공부시 합격여부 = 합격


### SVM(Support Vector Meachine)
서포트 벡터 머신은 데이터를 분류할 수 있는 선을 찾는다.
서포트 벡터 머신은 최적화된 선을 찾기 위해 A그룹과 B그룹의 가장 바깥쪽에 있는 데이터 간의 거리가 가장 멀리 떨어진 직선을 찾는다.
선형 서포트 벡터 머신은 초평면을 기준으로 객체 간에 마진을 최대화 되도록 분류하는 모델이다.

In [44]:
from sklearn import svm
x_train = train_feature
y_train = train_label_multi_classification
clfS = svm.SVC()
clfS = clf.fit(x_train, y_train)

In [45]:
for i in range(1,15):
    prediction = clfS.predict(np.array([[i]]))
    result = chr(prediction+64) if prediction != 0 else 'F'
    print(f'{i:2d}시간 공부시 학점 예측 = {result}')

 1시간 공부시 학점 예측 = F
 2시간 공부시 학점 예측 = F
 3시간 공부시 학점 예측 = F
 4시간 공부시 학점 예측 = F
 5시간 공부시 학점 예측 = C
 6시간 공부시 학점 예측 = C
 7시간 공부시 학점 예측 = B
 8시간 공부시 학점 예측 = B
 9시간 공부시 학점 예측 = B
10시간 공부시 학점 예측 = A
11시간 공부시 학점 예측 = A
12시간 공부시 학점 예측 = A
13시간 공부시 학점 예측 = A
14시간 공부시 학점 예측 = A
